server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Portfolio?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trade-execution-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 10
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
      retry:
        max-attempts: 3
      backoff:
        delay: 1000